name: credentials-obfuscation
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        otp_version: [24, 25, "26.0-rc3"]
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp_version }}
        rebar3-version: '3'
    - run: rebar3 compile
    - run: rebar3 dialyzer
    - run: rebar3 eunit
    - run: rebar3 ct --verbose --verbosity=3 --readable=true
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: ct-logs-${{matrix.os}}-${{matrix.otp_version}}
        path: _build/test/logs
